name: frontmatter-academico
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandoc
  - nodejs>=18
  - npm
  - git
  - jupyterlab
  - quarto
  - pip
  - pyyaml
  - pre-commit
  - pip:
      - mystmd
      - jupyter-book